pdPreviewHud = {}
--------------------------------------------------------------------------------
--  Handler.......... : onInit
--  Author........... :
--  Description...... :
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
function pdPreviewHud.onLoad ( hRenderView )
--------------------------------------------------------------------------------
    local hPdHud  = nil

    hPdHud = resource.createTemporary ( resource.kTypeHUD )
    if  ( hPdHud )
    then
        local hContainer = hud.newComponent ( hPdHud, hud.kComponentTypeContainer, "Container" )
        local hFont = resource.load ( resource.kTypeFont, "DefaultFont")

        if(hContainer)
        then
            --hud.setComponentParent ( hContainer, nil )
            hud.setComponentVisible ( hContainer, true )
            hud.setComponentActive ( hContainer, true )
            hud.setComponentIgnoredByMouse ( hContainer, false )
            hud.setComponentPosition ( hContainer, 50,  50)
            hud.setComponentOrigin ( hContainer, hud.kComponentOriginCenter )
            hud.setComponentSize ( hContainer, 100, 100 )
            hud.setComponentAdjustedToNearestPixels ( hContainer, false )
            --hud.setComponentAspectInvariant (  )
            hud.setComponentZOrder ( hContainer, 127 )

            hud.setComponentShapeType ( hContainer, hud.kShapeTypeRectangle )
            hud.setComponentOpacity ( hContainer, 255 )
            hud.setComponentBackgroundColor ( hContainer, 255,255,255,255)

            local hLogoText = hud.newComponent ( hPdHud, hud.kComponentTypeLabel, "LogoText" )
            hud.setComponentVisible ( hLogoText, true )
            hud.setComponentParent ( hLogoText, "Container" )
            hud.setComponentPosition ( hLogoText, 50,  47)
            hud.setComponentSize ( hLogoText, 89.220, 12.750 )
            hud.setComponentOpacity ( hLogoText, 168 )
            hud.setComponentZOrder          ( hLogoText, 127 )
            hud.setComponentBackgroundColor ( hLogoText, 0,0,0,0)
            hud.setLabelText ( hLogoText, "POLYGLOT-DIALOGUE" )
            hud.setLabelTextAlignment ( hLogoText, hud.kTextHAlignmentCenter, hud.kTextVAlignmentCenter )
            hud.setComponentForegroundColor ( hLogoText, 68, 34, 34, 255 )
            hud.setComponentBorderColor ( hLogoText, 0,0,0,0 )
            hud.setLabelTextEncoding ( hLogoText, hud.kTextEncodingUTF8 )
            hud.setLabelTextHeight ( hLogoText, 100 )
            --hud.setLabelTextLineSpacing ( hLogoText, 100 )
            --hud.setLabelFont ( hLogoText, hud.kfont )
            --hud.setLabelTextCase ( hLogoText, hud.kTextCaseVariable )
            --hud.setLabelTextLetterSpacing   ( hLogoText, 0 )
            --hud.setLabelTextLineSpacing     ( hLogoText, 0 )
            hud.setLabelFont ( hLogoText, hFont )
            hud.setComponentTextAntialiased ( hLogoText, true )

            local hPdActorNameText = hud.newComponent ( hPdHud, hud.kComponentTypeLabel, "pdActorNameText" )
            hud.setComponentParent ( hPdActorNameText, "Container" )
            hud.setComponentPosition ( hPdActorNameText, 50.250,  85.770)
            hud.setComponentSize ( hPdActorNameText, 90.270, 4.940 )
            hud.setComponentOpacity ( hPdActorNameText, 255 )
            hud.setComponentZOrder          ( hPdActorNameText, 127 )
            hud.setComponentBackgroundColor ( hPdActorNameText, 0,0,0,0)
            hud.setLabelText ( hPdActorNameText, "<% ACTORNAME %>" )
            hud.setLabelTextAlignment ( hPdActorNameText, hud.kTextHAlignmentCenter, hud.kTextVAlignmentCenter )
            hud.setComponentForegroundColor ( hPdActorNameText, 0, 0, 0, 255 )
            hud.setComponentBorderColor ( hPdActorNameText, 0,0,0,0 )
            hud.setLabelTextEncoding ( hPdActorNameText, hud.kTextEncodingUTF8 )
            hud.setLabelTextHeight ( hPdActorNameText, 100 )
            hud.setLabelTextCase ( hPdActorNameText, hud.kTextCaseVariable )
            hud.setLabelTextLetterSpacing   ( hPdActorNameText, 0 )
            hud.setLabelTextLineSpacing     ( hPdActorNameText, 0 )
            hud.setLabelFont ( hPdActorNameText, hFont )
            hud.setComponentTextAntialiased ( hPdActorNameText, true )

            local hPdBackground = hud.newComponent ( hPdHud, hud.kComponentTypeContainer, "pdBackground" )
            hud.setComponentParent ( hPdBackground,  "Container" )
            hud.setComponentVisible ( hPdBackground, true )
            hud.setComponentActive ( hPdBackground, true )
            hud.setComponentIgnoredByMouse ( hPdBackground, false )
            hud.setComponentPosition ( hPdBackground, 50,  50)
            hud.setComponentOrigin ( hPdBackground, hud.kComponentOriginCenter )
            hud.setComponentSize ( hPdBackground, 100, 100 )
            hud.setComponentAdjustedToNearestPixels ( hPdBackground, false )
            hud.setComponentZOrder ( hPdBackground, 124 )
            hud.setComponentShapeType ( hPdBackground, hud.kShapeTypeRectangle )
            hud.setComponentOpacity ( hPdBackground, 255 )
            hud.setComponentBackgroundColor ( hPdBackground, 255,255,255,255)

            local hBackgroundColor = hud.newComponent ( hPdHud, hud.kComponentTypeContainer, "pdBackgroundColor" )
            hud.setComponentParent ( hBackgroundColor,  "Container" )
            hud.setComponentVisible ( hBackgroundColor, true )
            hud.setComponentActive ( hBackgroundColor, true )
            hud.setComponentIgnoredByMouse ( hBackgroundColor, false )
            hud.setComponentPosition ( hBackgroundColor, 50,  50)
            hud.setComponentOrigin ( hBackgroundColor, hud.kComponentOriginCenter )
            hud.setComponentSize ( hBackgroundColor, 100, 100 )
            hud.setComponentAdjustedToNearestPixels ( hBackgroundColor, false )
            hud.setComponentZOrder ( hBackgroundColor, 123 )
            hud.setComponentShapeType ( hBackgroundColor, hud.kShapeTypeRectangle )
            hud.setComponentOpacity ( hBackgroundColor, 255 )
            hud.setComponentBackgroundColor ( hBackgroundColor, 255,255,255,255)

            local hPdBottomText = hud.newComponent ( hPdHud, hud.kComponentTypeButton, "pdBottomText" )
            hud.setComponentParent ( hPdBottomText, "Container" )
            hud.setComponentPosition ( hPdBottomText, 49.880,  11.340)
            hud.setComponentSize ( hPdBottomText, 90, 13 )
            hud.setComponentOpacity ( hPdBottomText, 255 )
            hud.setComponentZOrder          ( hPdBottomText, 127 )
            hud.setComponentBackgroundColor ( hPdBottomText, 255,255,255,255)
            hud.setButtonText ( hPdBottomText, "<% BOTTOM TEXT %>" )
            hud.setButtonTextAlignment ( hPdBottomText, hud.kTextHAlignmentCenter, hud.kTextVAlignmentCenter )
            hud.setComponentForegroundColor ( hPdBottomText, 0, 0, 0, 255 )
            hud.setComponentBorderColor ( hPdBottomText, 0,0,0,255 )
            hud.setButtonTextEncoding ( hPdBottomText, hud.kTextEncodingUTF8 )
            hud.setButtonTextHeight ( hPdBottomText, 50 )
            hud.setButtonTextCase ( hPdBottomText, hud.kTextCaseVariable )
            hud.setButtonTextLetterSpacing   ( hPdBottomText, 0 )
            hud.setButtonTextLineSpacing     ( hPdBottomText, 0 )
            hud.setButtonFont ( hPdBottomText, hFont )
            hud.setComponentTextAntialiased ( hPdBottomText, true )

            pdPreviewHud.pdDialogGroupChoice(hPdHud, "1", "Container", 49.980,  45.760, 89.930, 81.780  )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "1_1", "1", 50,  50.220,  100, 13 )
            pdPreviewHud.pdDialogGroupChoice(hPdHud, "2", "Container", 49.980,  45.760, 89.930, 81.780  )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "2_1", "2", 50,  59.320,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "2_2", "2", 50,  41.660,  100, 13 )
            pdPreviewHud.pdDialogGroupChoice(hPdHud, "3", "Container", 49.980,  45.760, 89.930, 81.780  )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "3_1", "3", 50,  67.620,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "3_2", "3", 50,  50.220,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "3_3", "3", 50,  32.290,  100, 13 )
            pdPreviewHud.pdDialogGroupChoice(hPdHud, "4", "Container", 49.980,  45.760, 89.930, 81.780  )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont,"4_1", "4", 50,  76.450,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "4_2", "4", 50,  59.320,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "4_3", "4", 50,  41.660,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "4_4", "4", 50,  24.000,  100, 13 )
            pdPreviewHud.pdDialogGroupChoice(hPdHud, "5", "Container", 49.980,  45.760, 89.930, 81.780  )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "5_1", "5", 50,  85.280,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "5_2", "5", 50,  67.620,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "5_3", "5", 50,  50.220,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "5_4", "5", 50,  32.290,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "5_5", "5", 50,  14.900,  100, 13 )
            pdPreviewHud.pdDialogGroupChoice(hPdHud, "6", "Container", 49.980,  45.760, 89.930, 81.780  )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "6_1", "6", 50,  93.500,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "6_2", "6", 50,  76.450,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "6_3", "6", 50,  59.320,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "6_4", "6", 50,  41.660,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "6_5", "6", 50,  24.900,  100, 13 )
            pdPreviewHud.pdDialogChoice(hPdHud, hFont, "6_6", "6", 50,  6.500,  100, 13 )

            local hPdDialogText = hud.newComponent ( hPdHud, hud.kComponentTypeButton, "pdDialogText" )
            hud.setComponentTag ( hPdDialogText, "pdDialogText" )
            hud.setComponentParent ( hPdDialogText, "Container" )
            hud.setComponentPosition ( hPdDialogText, 50, 16 )
            hud.setComponentSize ( hPdDialogText, 89.940, 22.30 )
            hud.setComponentOpacity ( hPdDialogText, 255 )
            hud.setComponentZOrder          ( hPdDialogText, 127 )
            hud.setComponentBackgroundColor ( hPdDialogText, 255,255,255,192)
            hud.setButtonText ( hPdDialogText, "<% DIALOGTEXT %>" )
            hud.setButtonTextAlignment ( hPdDialogText, hud.kTextHAlignmentCenter, hud.kTextVAlignmentCenter )
            hud.setComponentForegroundColor ( hPdDialogText, 0, 0, 0, 255 )
            hud.setComponentBorderColor ( hPdDialogText, 0,0,0,255 )
            hud.setButtonTextEncoding ( hPdDialogText, hud.kTextEncodingUTF8 )
            hud.setButtonTextHeight ( hPdDialogText, 25 )
            --hud.setLabelTextCase ( hPdDialogText, hud.kTextCaseVariable )
            --hud.setLabelTextLetterSpacing   ( hPdDialogText, 0 )
            --hud.setLabelTextLineSpacing     ( hPdDialogText, 0 )
            hud.setButtonFont ( hPdDialogText, hFont )
            --log.error ( hud.getComponentTag ( hPdDialogText ) )
            hud.setComponentTextAntialiased ( hPdDialogText, true )

            local hPdMovie = hud.newComponent ( hPdHud, hud.kComponentTypeMovie, "pdMovie" )
            hud.setComponentParent ( hPdMovie, "Container" )
            hud.setComponentPosition ( hPdMovie, 49.980, 45.600 )
            hud.setComponentSize ( hPdMovie, 89.940, 82.040 )
            hud.setComponentOpacity ( hPdMovie, 255 )
            hud.setComponentZOrder( hPdMovie, 127 )
            hud.setComponentBackgroundColor ( hPdMovie, 0,0,0,255)
            hud.setComponentForegroundColor ( hPdMovie, 255, 255, 255, 255 )
            hud.setComponentBorderColor ( hPdMovie, 127,127,127,255 )

            local hPdPageText = hud.newComponent ( hPdHud, hud.kComponentTypeButton, "pdPageText" )
            hud.setComponentParent ( hPdPageText, "Container" )
            hud.setComponentPosition ( hPdPageText, 49.980, 45.830 )
            hud.setComponentSize ( hPdPageText, 89.940, 70.690 )
            hud.setComponentOpacity ( hPdPageText, 255 )
            hud.setComponentZOrder          ( hPdPageText, 127 )
            hud.setComponentBackgroundColor ( hPdPageText, 0,0,0,0)
            hud.setButtonText ( hPdPageText, "<% PAGETEXT %>" )
            hud.setButtonTextAlignment ( hPdPageText, hud.kTextHAlignmentCenter, hud.kTextVAlignmentCenter )
            hud.setComponentForegroundColor ( hPdPageText, 0, 0, 0, 255 )
            hud.setComponentBorderColor ( hPdPageText, 0,0,0,255 )
            hud.setButtonTextEncoding ( hPdPageText, hud.kTextEncodingUTF8 )
            hud.setButtonTextHeight ( hPdPageText, 5 )
            --hud.setLabelTextCase ( hPdPageText, hud.kTextCaseVariable )
            --hud.setLabelTextLetterSpacing   ( hPdPageText, 0 )
            --hud.setLabelTextLineSpacing     ( hPdPageText, 0 )
            hud.setButtonFont ( hPdPageText, hFont )
            hud.setComponentTextAntialiased ( hPdPageText, true )

            local hPdSubTitleText = hud.newComponent ( hPdHud, hud.kComponentTypeLabel, "pdSubTitleText" )
            hud.setComponentParent ( hPdSubTitleText, "Container" )
            hud.setComponentPosition ( hPdSubTitleText, 50.170,  52.500)
            hud.setComponentSize ( hPdSubTitleText, 89.630, 5.210 )
            hud.setComponentOpacity ( hPdSubTitleText, 255 )
            hud.setComponentZOrder          ( hPdSubTitleText, 128 )
            hud.setComponentBackgroundColor ( hPdSubTitleText, 0,0,0,0)
            hud.setLabelText ( hPdSubTitleText, "<% SUBTITLE %>" )
            hud.setLabelTextAlignment ( hPdSubTitleText, hud.kTextHAlignmentCenter, hud.kTextVAlignmentCenter )
            hud.setComponentForegroundColor ( hPdSubTitleText, 0, 0, 0, 255 )
            hud.setComponentBorderColor ( hPdSubTitleText, 0,0,0,0 )
            hud.setLabelTextEncoding ( hPdSubTitleText, hud.kTextEncodingUTF8 )
            hud.setLabelTextHeight ( hPdSubTitleText, 100 )
            hud.setLabelTextCase ( hPdSubTitleText, hud.kTextCaseVariable )
            hud.setLabelTextLetterSpacing   ( hPdSubTitleText, 0 )
            hud.setLabelTextLineSpacing     ( hPdSubTitleText, 0 )
            hud.setLabelFont ( hPdSubTitleText, hFont )
            hud.setComponentTextAntialiased ( hPdSubTitleText, true )

            local hPdTitleText = hud.newComponent ( hPdHud, hud.kComponentTypeLabel, "pdTitleText" )
            hud.setComponentParent ( hPdTitleText, "Container" )
            hud.setComponentPosition ( hPdTitleText, 50.130,  61.270)
            hud.setComponentSize ( hPdTitleText, 89.730, 9.670 )
            hud.setComponentOpacity ( hPdTitleText, 255 )
            hud.setComponentZOrder          ( hPdTitleText, 128 )
            hud.setComponentBackgroundColor ( hPdTitleText, 0,0,0,0)
            hud.setLabelText ( hPdTitleText, "<% TITLE %>" )
            hud.setLabelTextAlignment ( hPdTitleText, hud.kTextHAlignmentCenter, hud.kTextVAlignmentCenter )
            hud.setComponentForegroundColor ( hPdTitleText, 0, 0, 0, 255 )
            hud.setComponentBorderColor ( hPdTitleText, 0,0,0,0 )
            hud.setLabelTextEncoding ( hPdTitleText, hud.kTextEncodingUTF8 )
            hud.setLabelTextHeight ( hPdTitleText, 100 )
            hud.setLabelTextCase ( hPdTitleText, hud.kTextCaseVariable )
            hud.setLabelTextLetterSpacing   ( hPdTitleText, 0 )
            hud.setLabelTextLineSpacing     ( hPdTitleText, 0 )
            hud.setLabelFont ( hPdTitleText, hFont )
            hud.setComponentTextAntialiased ( hPdTitleText, true )

            local hPdTopText = hud.newComponent ( hPdHud, hud.kComponentTypeButton, "pdTopText" )
            hud.setComponentParent ( hPdTopText, "Container" )
            hud.setComponentPosition ( hPdTopText, 50, 80.150 )
            hud.setComponentSize ( hPdTopText, 90, 13 )
            hud.setComponentOpacity ( hPdTopText, 255 )
            hud.setComponentZOrder          ( hPdTopText, 127 )
            hud.setComponentBackgroundColor ( hPdTopText, 255,255,255,255)
            hud.setButtonText ( hPdTopText, "<% TOPTEXT %>" )
            hud.setButtonTextAlignment ( hPdTopText, hud.kTextHAlignmentCenter, hud.kTextVAlignmentCenter )
            hud.setComponentForegroundColor ( hPdTopText, 0, 0, 0, 255 )
            hud.setComponentBorderColor ( hPdTopText, 0,0,0,255 )
            hud.setButtonTextEncoding ( hPdTopText, hud.kTextEncodingUTF8 )
            hud.setButtonTextHeight ( hPdTopText, 50 )
            -- hud.setLabelTextCase ( hPdTopText, hud.kTextCaseVariable )
            -- hud.setLabelTextLetterSpacing   ( hPdTopText, 0 )
            --hud.setLabelTextLineSpacing     ( hPdTopText, 0 )
            hud.setButtonFont ( hPdTopText, hFont )
            --log.error ( hud.getComponentTag ( hPdTopText ) )
            hud.setComponentTextAntialiased ( hPdTopText, true )
        end
    end

    return hPdHud
--------------------------------------------------------------------------------
end
--------------------------------------------------------------------------------

function pdPreviewHud.pdDialogGroupChoice( hPdHud, sIndex, sParentName, nPosX, nPosY, nSizeX, nSizeY )
    local hPdDialogGroupChoice_1 = hud.newComponent ( hPdHud, hud.kComponentTypeContainer, "pdDialogGroupChoice_" .. sIndex )
    hud.setComponentTag ( hPdDialogGroupChoice_1, "pdDialogGroupChoice_" .. sIndex )
    hud.setComponentParent ( hPdDialogGroupChoice_1, sParentName )
    hud.setComponentVisible ( hPdDialogGroupChoice_1, true )
    hud.setComponentActive ( hPdDialogGroupChoice_1, true )
    hud.setComponentIgnoredByMouse ( hPdDialogGroupChoice_1, false )
    hud.setComponentPosition ( hPdDialogGroupChoice_1,  nPosX, nPosY)
    hud.setComponentOrigin ( hPdDialogGroupChoice_1, hud.kComponentOriginCenter )
    hud.setComponentSize ( hPdDialogGroupChoice_1, nSizeX, nSizeY )
    hud.setComponentAdjustedToNearestPixels ( hPdDialogGroupChoice_1, false )
    hud.setComponentZOrder ( hPdDialogGroupChoice_1, 127 )
    hud.setComponentShapeType ( hPdDialogGroupChoice_1, hud.kShapeTypeRectangle )
    hud.setComponentOpacity ( hPdDialogGroupChoice_1, 255 )
    hud.setComponentBackgroundColor ( hPdDialogGroupChoice_1, 0,0,0,0)
    hud.setComponentBorderColor ( hPdDialogGroupChoice_1, 0,0,0,0 )
end

function pdPreviewHud.pdDialogChoice( hPdHud, hFont, sIndex, sParentIndex, nPosX, nPosY, nSizeX, nSizeY )
    local hPdDialogChoice_1_1 = hud.newComponent ( hPdHud, hud.kComponentTypeButton, "pdDialogChoice_" .. sIndex )
    hud.setComponentTag ( hPdDialogChoice_1_1, "pdDialogChoice_" .. sIndex )
    hud.setComponentParent ( hPdDialogChoice_1_1, "pdDialogGroupChoice_" .. sParentIndex )
    hud.setComponentPosition ( hPdDialogChoice_1_1, nPosX, nPosY )
    hud.setComponentSize ( hPdDialogChoice_1_1, nSizeX, nSizeY )
    hud.setComponentOpacity ( hPdDialogChoice_1_1, 255 )
    hud.setComponentZOrder          ( hPdDialogChoice_1_1, 127 )
    hud.setComponentBackgroundColor ( hPdDialogChoice_1_1, 255, 255, 255, 160)
    hud.setButtonText ( hPdDialogChoice_1_1, "<% DIALOGCHOICE %>" )
    hud.setButtonTextAlignment ( hPdDialogChoice_1_1, hud.kTextHAlignmentCenter, hud.kTextVAlignmentCenter )
    hud.setComponentForegroundColor ( hPdDialogChoice_1_1, 0, 0, 0, 255 )
    hud.setComponentBorderColor ( hPdDialogChoice_1_1, 0,0,0,255 )
    hud.setButtonTextEncoding ( hPdDialogChoice_1_1, hud.kTextEncodingUTF8 )
    hud.setButtonTextHeight ( hPdDialogChoice_1_1, 50 )
    --hud.setLabelTextCase ( hPdDialogChoice_1_1, hud.kTextCaseVariable )
    --hud.setLabelTextLetterSpacing   ( hPdDialogChoice_1_1, 0 )
    --hud.setLabelTextLineSpacing     ( hPdDialogChoice_1_1, 0 )
    hud.setButtonFont ( hPdDialogChoice_1_1, hFont )
    hud.setComponentTextAntialiased ( hPdDialogChoice_1_1, true )
end